question_data = [
                     {"category": "Science: Mathematics",
                      "type": "boolean",
                      "difficulty": "easy",
                      "question": "A universal set, or a set that contains all sets, exists.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "Alaska is the largest state in the United States.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                      "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                      "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "History", "type": "boolean", "difficulty": "easy",
                      "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "History", "type": "boolean", "difficulty": "easy",
                      "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                      "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                      "question": "A scalene triangle has two sides of equal length.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Animals", "type": "boolean", "difficulty": "easy",
                      "question": "Rabbits are carnivores.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                      "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
                      "incorrect_answers": ["True"]}]
